"""empty message

Revision ID: 55ea8d649d12
Revises: 
Create Date: 2025-01-19 01:12:57.535180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ea8d649d12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_usage', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('balance_earned', sa.BigInteger(), nullable=True),
    sa.Column('balance_deposit', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('work',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('work_time', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('workprocess',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('price', sa.DateTime(), nullable=True),
    sa.Column('worker', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['work.id'], ),
    sa.ForeignKeyConstraint(['worker'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workprocess')
    op.drop_table('work')
    op.drop_table('user')
    # ### end Alembic commands ###
